apiVersion: v1
kind: Secret
metadata:
  name: k8s-agent-secrets
type: Opaque
stringData:
  ca_cert: <base64 encoded kubernetes ca cert>
  cf_api_token: <codefresh api key>
  sa_token: <encoded kubernetes sa token>