{{- if and .Values.rbacEnabled (not .Values.existingServiceAccount) }}
{{- if .Values.useNamespaceWideRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname" . }}-cluster-reader
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.useNamespaceWideRole }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ template "fullname" . }}-cluster-reader
{{- end }}
