{{- if and .Values.rbacEnabled (not .Values.useNamespaceWideRole) (not .Values.existingServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-rollback
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
{{- end }}
