/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.exportSymbol('proto.hapi.release.Hook', null, global);
goog.exportSymbol('proto.hapi.release.Hook.DeletePolicy', null, global);
goog.exportSymbol('proto.hapi.release.Hook.Event', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.release.Hook = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hapi.release.Hook.repeatedFields_, null);
};
goog.inherits(proto.hapi.release.Hook, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.release.Hook.displayName = 'proto.hapi.release.Hook';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hapi.release.Hook.repeatedFields_ = [5,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.release.Hook.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.release.Hook.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.release.Hook} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.release.Hook.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    kind: jspb.Message.getFieldWithDefault(msg, 2, ""),
    path: jspb.Message.getFieldWithDefault(msg, 3, ""),
    manifest: jspb.Message.getFieldWithDefault(msg, 4, ""),
    eventsList: jspb.Message.getRepeatedField(msg, 5),
    lastRun: (f = msg.getLastRun()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    weight: jspb.Message.getFieldWithDefault(msg, 7, 0),
    deletePoliciesList: jspb.Message.getRepeatedField(msg, 8)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.release.Hook}
 */
proto.hapi.release.Hook.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.release.Hook;
  return proto.hapi.release.Hook.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.release.Hook} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.release.Hook}
 */
proto.hapi.release.Hook.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKind(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setManifest(value);
      break;
    case 5:
      var value = /** @type {!Array.<!proto.hapi.release.Hook.Event>} */ (reader.readPackedEnum());
      msg.setEventsList(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastRun(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeight(value);
      break;
    case 8:
      var value = /** @type {!Array.<!proto.hapi.release.Hook.DeletePolicy>} */ (reader.readPackedEnum());
      msg.setDeletePoliciesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.release.Hook.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.release.Hook.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.release.Hook} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.release.Hook.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKind();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getManifest();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      5,
      f
    );
  }
  f = message.getLastRun();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getDeletePoliciesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.hapi.release.Hook.Event = {
  UNKNOWN: 0,
  PRE_INSTALL: 1,
  POST_INSTALL: 2,
  PRE_DELETE: 3,
  POST_DELETE: 4,
  PRE_UPGRADE: 5,
  POST_UPGRADE: 6,
  PRE_ROLLBACK: 7,
  POST_ROLLBACK: 8,
  RELEASE_TEST_SUCCESS: 9,
  RELEASE_TEST_FAILURE: 10
};

/**
 * @enum {number}
 */
proto.hapi.release.Hook.DeletePolicy = {
  SUCCEEDED: 0,
  FAILED: 1
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.hapi.release.Hook.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.hapi.release.Hook.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string kind = 2;
 * @return {string}
 */
proto.hapi.release.Hook.prototype.getKind = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.hapi.release.Hook.prototype.setKind = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.hapi.release.Hook.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.hapi.release.Hook.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string manifest = 4;
 * @return {string}
 */
proto.hapi.release.Hook.prototype.getManifest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.hapi.release.Hook.prototype.setManifest = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Event events = 5;
 * @return {!Array.<!proto.hapi.release.Hook.Event>}
 */
proto.hapi.release.Hook.prototype.getEventsList = function() {
  return /** @type {!Array.<!proto.hapi.release.Hook.Event>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array.<!proto.hapi.release.Hook.Event>} value */
proto.hapi.release.Hook.prototype.setEventsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!proto.hapi.release.Hook.Event} value
 * @param {number=} opt_index
 */
proto.hapi.release.Hook.prototype.addEvents = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.hapi.release.Hook.prototype.clearEventsList = function() {
  this.setEventsList([]);
};


/**
 * optional google.protobuf.Timestamp last_run = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.hapi.release.Hook.prototype.getLastRun = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.hapi.release.Hook.prototype.setLastRun = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.hapi.release.Hook.prototype.clearLastRun = function() {
  this.setLastRun(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.release.Hook.prototype.hasLastRun = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 weight = 7;
 * @return {number}
 */
proto.hapi.release.Hook.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.hapi.release.Hook.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated DeletePolicy delete_policies = 8;
 * @return {!Array.<!proto.hapi.release.Hook.DeletePolicy>}
 */
proto.hapi.release.Hook.prototype.getDeletePoliciesList = function() {
  return /** @type {!Array.<!proto.hapi.release.Hook.DeletePolicy>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array.<!proto.hapi.release.Hook.DeletePolicy>} value */
proto.hapi.release.Hook.prototype.setDeletePoliciesList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!proto.hapi.release.Hook.DeletePolicy} value
 * @param {number=} opt_index
 */
proto.hapi.release.Hook.prototype.addDeletePolicies = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.hapi.release.Hook.prototype.clearDeletePoliciesList = function() {
  this.setDeletePoliciesList([]);
};


goog.object.extend(exports, proto.hapi.release);
