/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var hapi_release_test_suite_pb = require('../../hapi/release/test_suite_pb.js');
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.exportSymbol('proto.hapi.release.Status', null, global);
goog.exportSymbol('proto.hapi.release.Status.Code', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.release.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.release.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.release.Status.displayName = 'proto.hapi.release.Status';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.release.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.release.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.release.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.release.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    resources: jspb.Message.getFieldWithDefault(msg, 3, ""),
    notes: jspb.Message.getFieldWithDefault(msg, 4, ""),
    lastTestSuiteRun: (f = msg.getLastTestSuiteRun()) && hapi_release_test_suite_pb.TestSuite.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.release.Status}
 */
proto.hapi.release.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.release.Status;
  return proto.hapi.release.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.release.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.release.Status}
 */
proto.hapi.release.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.hapi.release.Status.Code} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setResources(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotes(value);
      break;
    case 5:
      var value = new hapi_release_test_suite_pb.TestSuite;
      reader.readMessage(value,hapi_release_test_suite_pb.TestSuite.deserializeBinaryFromReader);
      msg.setLastTestSuiteRun(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.release.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.release.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.release.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.release.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getResources();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNotes();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLastTestSuiteRun();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      hapi_release_test_suite_pb.TestSuite.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.hapi.release.Status.Code = {
  UNKNOWN: 0,
  DEPLOYED: 1,
  DELETED: 2,
  SUPERSEDED: 3,
  FAILED: 4,
  DELETING: 5,
  PENDING_INSTALL: 6,
  PENDING_UPGRADE: 7,
  PENDING_ROLLBACK: 8
};

/**
 * optional Code code = 1;
 * @return {!proto.hapi.release.Status.Code}
 */
proto.hapi.release.Status.prototype.getCode = function() {
  return /** @type {!proto.hapi.release.Status.Code} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.hapi.release.Status.Code} value */
proto.hapi.release.Status.prototype.setCode = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string resources = 3;
 * @return {string}
 */
proto.hapi.release.Status.prototype.getResources = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.hapi.release.Status.prototype.setResources = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string notes = 4;
 * @return {string}
 */
proto.hapi.release.Status.prototype.getNotes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.hapi.release.Status.prototype.setNotes = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional TestSuite last_test_suite_run = 5;
 * @return {?proto.hapi.release.TestSuite}
 */
proto.hapi.release.Status.prototype.getLastTestSuiteRun = function() {
  return /** @type{?proto.hapi.release.TestSuite} */ (
    jspb.Message.getWrapperField(this, hapi_release_test_suite_pb.TestSuite, 5));
};


/** @param {?proto.hapi.release.TestSuite|undefined} value */
proto.hapi.release.Status.prototype.setLastTestSuiteRun = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.hapi.release.Status.prototype.clearLastTestSuiteRun = function() {
  this.setLastTestSuiteRun(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.release.Status.prototype.hasLastTestSuiteRun = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.hapi.release);
