/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var hapi_release_info_pb = require('../../hapi/release/info_pb.js');
var hapi_release_release_pb = require('../../hapi/release/release_pb.js');
goog.exportSymbol('proto.hapi.services.rudder.DeleteReleaseRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.DeleteReleaseResponse', null, global);
goog.exportSymbol('proto.hapi.services.rudder.InstallReleaseRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.InstallReleaseResponse', null, global);
goog.exportSymbol('proto.hapi.services.rudder.ReleaseStatusRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.ReleaseStatusResponse', null, global);
goog.exportSymbol('proto.hapi.services.rudder.Result', null, global);
goog.exportSymbol('proto.hapi.services.rudder.Result.Status', null, global);
goog.exportSymbol('proto.hapi.services.rudder.RollbackReleaseRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.RollbackReleaseResponse', null, global);
goog.exportSymbol('proto.hapi.services.rudder.UpgradeReleaseRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.UpgradeReleaseResponse', null, global);
goog.exportSymbol('proto.hapi.services.rudder.VersionReleaseRequest', null, global);
goog.exportSymbol('proto.hapi.services.rudder.VersionReleaseResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.Result = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hapi.services.rudder.Result.repeatedFields_, null);
};
goog.inherits(proto.hapi.services.rudder.Result, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.Result.displayName = 'proto.hapi.services.rudder.Result';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hapi.services.rudder.Result.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.Result.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.Result.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.Result} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.Result.toObject = function(includeInstance, msg) {
  var f, obj = {
    info: jspb.Message.getFieldWithDefault(msg, 1, ""),
    logList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.Result.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.Result;
  return proto.hapi.services.rudder.Result.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.Result} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.Result.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInfo(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addLog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.Result.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.Result.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.Result} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.Result.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLogList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.hapi.services.rudder.Result.Status = {
  UNKNOWN: 0,
  SUCCESS: 1,
  UNCHANGED: 2,
  ERROR: 3
};

/**
 * optional string info = 1;
 * @return {string}
 */
proto.hapi.services.rudder.Result.prototype.getInfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.hapi.services.rudder.Result.prototype.setInfo = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string log = 2;
 * @return {!Array.<string>}
 */
proto.hapi.services.rudder.Result.prototype.getLogList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array.<string>} value */
proto.hapi.services.rudder.Result.prototype.setLogList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.hapi.services.rudder.Result.prototype.addLog = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.hapi.services.rudder.Result.prototype.clearLogList = function() {
  this.setLogList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.VersionReleaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.VersionReleaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.VersionReleaseRequest.displayName = 'proto.hapi.services.rudder.VersionReleaseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.VersionReleaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.VersionReleaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.VersionReleaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.VersionReleaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.VersionReleaseRequest}
 */
proto.hapi.services.rudder.VersionReleaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.VersionReleaseRequest;
  return proto.hapi.services.rudder.VersionReleaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.VersionReleaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.VersionReleaseRequest}
 */
proto.hapi.services.rudder.VersionReleaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.VersionReleaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.VersionReleaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.VersionReleaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.VersionReleaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.VersionReleaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.VersionReleaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.VersionReleaseResponse.displayName = 'proto.hapi.services.rudder.VersionReleaseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.VersionReleaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.VersionReleaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.VersionReleaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.VersionReleaseResponse}
 */
proto.hapi.services.rudder.VersionReleaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.VersionReleaseResponse;
  return proto.hapi.services.rudder.VersionReleaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.VersionReleaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.VersionReleaseResponse}
 */
proto.hapi.services.rudder.VersionReleaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.VersionReleaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.VersionReleaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.VersionReleaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.hapi.services.rudder.VersionReleaseResponse.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.InstallReleaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.InstallReleaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.InstallReleaseRequest.displayName = 'proto.hapi.services.rudder.InstallReleaseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.InstallReleaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.InstallReleaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.InstallReleaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.InstallReleaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.InstallReleaseRequest}
 */
proto.hapi.services.rudder.InstallReleaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.InstallReleaseRequest;
  return proto.hapi.services.rudder.InstallReleaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.InstallReleaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.InstallReleaseRequest}
 */
proto.hapi.services.rudder.InstallReleaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.InstallReleaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.InstallReleaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.InstallReleaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.InstallReleaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.InstallReleaseRequest.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.InstallReleaseRequest.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.InstallReleaseRequest.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.InstallReleaseRequest.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.InstallReleaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.InstallReleaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.InstallReleaseResponse.displayName = 'proto.hapi.services.rudder.InstallReleaseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.InstallReleaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.InstallReleaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.InstallReleaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.hapi.services.rudder.Result.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.InstallReleaseResponse}
 */
proto.hapi.services.rudder.InstallReleaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.InstallReleaseResponse;
  return proto.hapi.services.rudder.InstallReleaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.InstallReleaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.InstallReleaseResponse}
 */
proto.hapi.services.rudder.InstallReleaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 2:
      var value = new proto.hapi.services.rudder.Result;
      reader.readMessage(value,proto.hapi.services.rudder.Result.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.InstallReleaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.InstallReleaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.InstallReleaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.hapi.services.rudder.Result.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.InstallReleaseResponse.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Result result = 2;
 * @return {?proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.getResult = function() {
  return /** @type{?proto.hapi.services.rudder.Result} */ (
    jspb.Message.getWrapperField(this, proto.hapi.services.rudder.Result, 2));
};


/** @param {?proto.hapi.services.rudder.Result|undefined} value */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.setResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.InstallReleaseResponse.prototype.clearResult = function() {
  this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.InstallReleaseResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.DeleteReleaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.DeleteReleaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.DeleteReleaseRequest.displayName = 'proto.hapi.services.rudder.DeleteReleaseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.DeleteReleaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.DeleteReleaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.DeleteReleaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.DeleteReleaseRequest}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.DeleteReleaseRequest;
  return proto.hapi.services.rudder.DeleteReleaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.DeleteReleaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.DeleteReleaseRequest}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.DeleteReleaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.DeleteReleaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.DeleteReleaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.DeleteReleaseRequest.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.DeleteReleaseRequest.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.DeleteReleaseRequest.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.DeleteReleaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.DeleteReleaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.DeleteReleaseResponse.displayName = 'proto.hapi.services.rudder.DeleteReleaseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.DeleteReleaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.DeleteReleaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.DeleteReleaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.hapi.services.rudder.Result.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.DeleteReleaseResponse}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.DeleteReleaseResponse;
  return proto.hapi.services.rudder.DeleteReleaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.DeleteReleaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.DeleteReleaseResponse}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 2:
      var value = new proto.hapi.services.rudder.Result;
      reader.readMessage(value,proto.hapi.services.rudder.Result.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.DeleteReleaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.DeleteReleaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.DeleteReleaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.hapi.services.rudder.Result.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.DeleteReleaseResponse.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Result result = 2;
 * @return {?proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.getResult = function() {
  return /** @type{?proto.hapi.services.rudder.Result} */ (
    jspb.Message.getWrapperField(this, proto.hapi.services.rudder.Result, 2));
};


/** @param {?proto.hapi.services.rudder.Result|undefined} value */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.setResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.DeleteReleaseResponse.prototype.clearResult = function() {
  this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.DeleteReleaseResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.UpgradeReleaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.UpgradeReleaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.UpgradeReleaseRequest.displayName = 'proto.hapi.services.rudder.UpgradeReleaseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.UpgradeReleaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.UpgradeReleaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    current: (f = msg.getCurrent()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    target: (f = msg.getTarget()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    timeout: jspb.Message.getFieldWithDefault(msg, 3, 0),
    wait: jspb.Message.getFieldWithDefault(msg, 4, false),
    recreate: jspb.Message.getFieldWithDefault(msg, 5, false),
    force: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.UpgradeReleaseRequest}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.UpgradeReleaseRequest;
  return proto.hapi.services.rudder.UpgradeReleaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.UpgradeReleaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.UpgradeReleaseRequest}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setCurrent(value);
      break;
    case 2:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeout(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWait(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecreate(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.UpgradeReleaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.UpgradeReleaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getWait();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getRecreate();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getForce();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional hapi.release.Release current = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getCurrent = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setCurrent = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.clearCurrent = function() {
  this.setCurrent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.hasCurrent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional hapi.release.Release target = 2;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getTarget = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 2));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setTarget = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.clearTarget = function() {
  this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 Timeout = 3;
 * @return {number}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setTimeout = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool Wait = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getWait = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setWait = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool Recreate = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getRecreate = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setRecreate = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool Force = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.getForce = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.UpgradeReleaseRequest.prototype.setForce = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.UpgradeReleaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.UpgradeReleaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.UpgradeReleaseResponse.displayName = 'proto.hapi.services.rudder.UpgradeReleaseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.UpgradeReleaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.UpgradeReleaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.hapi.services.rudder.Result.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.UpgradeReleaseResponse}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.UpgradeReleaseResponse;
  return proto.hapi.services.rudder.UpgradeReleaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.UpgradeReleaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.UpgradeReleaseResponse}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 2:
      var value = new proto.hapi.services.rudder.Result;
      reader.readMessage(value,proto.hapi.services.rudder.Result.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.UpgradeReleaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.UpgradeReleaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.hapi.services.rudder.Result.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Result result = 2;
 * @return {?proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.getResult = function() {
  return /** @type{?proto.hapi.services.rudder.Result} */ (
    jspb.Message.getWrapperField(this, proto.hapi.services.rudder.Result, 2));
};


/** @param {?proto.hapi.services.rudder.Result|undefined} value */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.setResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.clearResult = function() {
  this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.UpgradeReleaseResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.RollbackReleaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.RollbackReleaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.RollbackReleaseRequest.displayName = 'proto.hapi.services.rudder.RollbackReleaseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.RollbackReleaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.RollbackReleaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.RollbackReleaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    current: (f = msg.getCurrent()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    target: (f = msg.getTarget()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    timeout: jspb.Message.getFieldWithDefault(msg, 3, 0),
    wait: jspb.Message.getFieldWithDefault(msg, 4, false),
    recreate: jspb.Message.getFieldWithDefault(msg, 5, false),
    force: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.RollbackReleaseRequest}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.RollbackReleaseRequest;
  return proto.hapi.services.rudder.RollbackReleaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.RollbackReleaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.RollbackReleaseRequest}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setCurrent(value);
      break;
    case 2:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeout(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWait(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecreate(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.RollbackReleaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.RollbackReleaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.RollbackReleaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getWait();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getRecreate();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getForce();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional hapi.release.Release current = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getCurrent = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setCurrent = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.RollbackReleaseRequest.prototype.clearCurrent = function() {
  this.setCurrent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.hasCurrent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional hapi.release.Release target = 2;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getTarget = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 2));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setTarget = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.RollbackReleaseRequest.prototype.clearTarget = function() {
  this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 Timeout = 3;
 * @return {number}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setTimeout = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool Wait = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getWait = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setWait = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool Recreate = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getRecreate = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setRecreate = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool Force = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.getForce = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.hapi.services.rudder.RollbackReleaseRequest.prototype.setForce = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.RollbackReleaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.RollbackReleaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.RollbackReleaseResponse.displayName = 'proto.hapi.services.rudder.RollbackReleaseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.RollbackReleaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.RollbackReleaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.RollbackReleaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.hapi.services.rudder.Result.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.RollbackReleaseResponse}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.RollbackReleaseResponse;
  return proto.hapi.services.rudder.RollbackReleaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.RollbackReleaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.RollbackReleaseResponse}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 2:
      var value = new proto.hapi.services.rudder.Result;
      reader.readMessage(value,proto.hapi.services.rudder.Result.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.RollbackReleaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.RollbackReleaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.RollbackReleaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.hapi.services.rudder.Result.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.RollbackReleaseResponse.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Result result = 2;
 * @return {?proto.hapi.services.rudder.Result}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.getResult = function() {
  return /** @type{?proto.hapi.services.rudder.Result} */ (
    jspb.Message.getWrapperField(this, proto.hapi.services.rudder.Result, 2));
};


/** @param {?proto.hapi.services.rudder.Result|undefined} value */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.setResult = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.RollbackReleaseResponse.prototype.clearResult = function() {
  this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.RollbackReleaseResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.ReleaseStatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.ReleaseStatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.ReleaseStatusRequest.displayName = 'proto.hapi.services.rudder.ReleaseStatusRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.ReleaseStatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.ReleaseStatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.ReleaseStatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.ReleaseStatusRequest}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.ReleaseStatusRequest;
  return proto.hapi.services.rudder.ReleaseStatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.ReleaseStatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.ReleaseStatusRequest}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.ReleaseStatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.ReleaseStatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.ReleaseStatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.ReleaseStatusRequest.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.ReleaseStatusRequest.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.ReleaseStatusRequest.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hapi.services.rudder.ReleaseStatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hapi.services.rudder.ReleaseStatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hapi.services.rudder.ReleaseStatusResponse.displayName = 'proto.hapi.services.rudder.ReleaseStatusResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hapi.services.rudder.ReleaseStatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hapi.services.rudder.ReleaseStatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.ReleaseStatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    release: (f = msg.getRelease()) && hapi_release_release_pb.Release.toObject(includeInstance, f),
    info: (f = msg.getInfo()) && hapi_release_info_pb.Info.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hapi.services.rudder.ReleaseStatusResponse}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hapi.services.rudder.ReleaseStatusResponse;
  return proto.hapi.services.rudder.ReleaseStatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hapi.services.rudder.ReleaseStatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hapi.services.rudder.ReleaseStatusResponse}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hapi_release_release_pb.Release;
      reader.readMessage(value,hapi_release_release_pb.Release.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 2:
      var value = new hapi_release_info_pb.Info;
      reader.readMessage(value,hapi_release_info_pb.Info.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hapi.services.rudder.ReleaseStatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hapi.services.rudder.ReleaseStatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hapi.services.rudder.ReleaseStatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hapi_release_release_pb.Release.serializeBinaryToWriter
    );
  }
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      hapi_release_info_pb.Info.serializeBinaryToWriter
    );
  }
};


/**
 * optional hapi.release.Release release = 1;
 * @return {?proto.hapi.release.Release}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.getRelease = function() {
  return /** @type{?proto.hapi.release.Release} */ (
    jspb.Message.getWrapperField(this, hapi_release_release_pb.Release, 1));
};


/** @param {?proto.hapi.release.Release|undefined} value */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.hapi.services.rudder.ReleaseStatusResponse.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional hapi.release.Info info = 2;
 * @return {?proto.hapi.release.Info}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.getInfo = function() {
  return /** @type{?proto.hapi.release.Info} */ (
    jspb.Message.getWrapperField(this, hapi_release_info_pb.Info, 2));
};


/** @param {?proto.hapi.release.Info|undefined} value */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.setInfo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.hapi.services.rudder.ReleaseStatusResponse.prototype.clearInfo = function() {
  this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hapi.services.rudder.ReleaseStatusResponse.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.hapi.services.rudder);
